import { loadExampleEmergenceClaimBundle } from './claim';
import {
  buildHistoricalEmergenceRecord,
  createEmergenceClaim,
  markClaimCandidate,
  markClaimNotCandidate,
  ratifyEmergenceClaim,
  recordPredictionEvaluation,
  retractEmergenceClaim,
} from './claim';
import {
  AGENT_0_GENESIS_AGENT_ID_SEED,
  AGENT_0_GENESIS_PROFILE,
  DEFAULT_MONAD_MARKET_ID,
  EMERGENCE_RECORDER_ABI,
  FIRST_ECOSYSTEM_AGENT_PROFILE,
  LIVE_REVENUE_ROUTER_ADDRESS,
  MONAD_MAINNET_CHAIN_ID,
  assertValidBigFiveProfile,
  buildAgentDecision,
  createLocalBehavioralClaim,
  encodeAgentProfile,
  executeAgentDecision,
  getOnchainAgentScores,
  hashJson,
  profileHash,
  registerAgentProfileOnchain,
  recordDecisionOnchain,
  routeCompletePsychometricProfile,
  routeBigFiveProfile,
  runLiveAgentProof,
  scaleDarkTriadRawToUint8,
  stableStringify,
} from './live-agent';
import type {
  ActiveOrganismSubsystemSnapshotRef,
  CausalSetEmergenceClaim,
  CreateEmergenceClaimInput,
  CreateAnyEmergenceClaimInput,
  CreateCausalSetEmergenceClaimInput,
  CreateFullFieldEmergenceClaimInput,
  EmergenceClaim,
  EmergenceCausalNecessityArgument,
  EmergenceClaimState,
  EmergenceEvidenceRef,
  EmergenceEventWindow,
  EmergenceFalsifiablePrediction,
  EmergenceNotificationSurface,
  EmergencePredictionEvaluationRecord,
  EmergenceRatificationRecord,
  EmergenceRetractionRecord,
  EmergenceStreamSnapshotRef,
  EmergenceTier,
  FullFieldEmergenceClaim,
  HistoricalEmergenceRecord,
  PredictionOutcome,
  PredictionScope,
  PromoteEmergenceClaimInput,
  RatifyEmergenceClaimInput,
  RecordPredictionEvaluationInput,
  RetractionBasis,
  RejectEmergenceClaimInput,
  RetractEmergenceClaimInput,
} from './types';
import type {
  AgentAction,
  AgentDecision,
  AgentDomain,
  AgentProfileEnvelope,
  BigFiveProfile,
  BigFiveFacetScores,
  ChainDecisionContext,
  CompletePsychometricProfile,
  DarkTriadProfile,
  DarkTriadScore,
  DoveMonitoringFlags,
  InstrumentVersions,
  LiveAgentProof,
  OnchainAgentRegistrationProof,
  OnchainRecordProof,
  RoutingResult,
  RoutedAgentProfile,
  RunLiveAgentConfig,
  TradingAction,
} from './live-agent';

export {
  buildHistoricalEmergenceRecord,
  createEmergenceClaim,
  markClaimCandidate,
  markClaimNotCandidate,
  ratifyEmergenceClaim,
  AGENT_0_GENESIS_AGENT_ID_SEED,
  AGENT_0_GENESIS_PROFILE,
  DEFAULT_MONAD_MARKET_ID,
  EMERGENCE_RECORDER_ABI,
  FIRST_ECOSYSTEM_AGENT_PROFILE,
  LIVE_REVENUE_ROUTER_ADDRESS,
  MONAD_MAINNET_CHAIN_ID,
  assertValidBigFiveProfile,
  buildAgentDecision,
  createLocalBehavioralClaim,
  encodeAgentProfile,
  executeAgentDecision,
  getOnchainAgentScores,
  hashJson,
  profileHash,
  registerAgentProfileOnchain,
  recordDecisionOnchain,
  routeCompletePsychometricProfile,
  routeBigFiveProfile,
  runLiveAgentProof,
  scaleDarkTriadRawToUint8,
  stableStringify,
  recordPredictionEvaluation,
  retractEmergenceClaim,
};

export type {
  AgentAction,
  AgentDecision,
  AgentDomain,
  AgentProfileEnvelope,
  ActiveOrganismSubsystemSnapshotRef,
  BigFiveProfile,
  BigFiveFacetScores,
  CausalSetEmergenceClaim,
  ChainDecisionContext,
  CompletePsychometricProfile,
  CreateEmergenceClaimInput,
  CreateAnyEmergenceClaimInput,
  CreateCausalSetEmergenceClaimInput,
  CreateFullFieldEmergenceClaimInput,
  EmergenceClaim,
  EmergenceCausalNecessityArgument,
  EmergenceClaimState,
  EmergenceEvidenceRef,
  EmergenceEventWindow,
  EmergenceFalsifiablePrediction,
  EmergenceNotificationSurface,
  EmergencePredictionEvaluationRecord,
  EmergenceRatificationRecord,
  EmergenceRetractionRecord,
  EmergenceStreamSnapshotRef,
  EmergenceTier,
  DarkTriadProfile,
  DarkTriadScore,
  DoveMonitoringFlags,
  FullFieldEmergenceClaim,
  HistoricalEmergenceRecord,
  InstrumentVersions,
  LiveAgentProof,
  OnchainAgentRegistrationProof,
  OnchainRecordProof,
  PredictionOutcome,
  PredictionScope,
  PromoteEmergenceClaimInput,
  RatifyEmergenceClaimInput,
  RecordPredictionEvaluationInput,
  RetractionBasis,
  RejectEmergenceClaimInput,
  RoutingResult,
  RoutedAgentProfile,
  RunLiveAgentConfig,
  TradingAction,
  RetractEmergenceClaimInput,
};

function main() {
  const bundle = loadExampleEmergenceClaimBundle();
  process.stdout.write(`${JSON.stringify(bundle, null, 2)}\n`);
}

if (require.main === module) {
  try {
    main();
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(message);
    process.exitCode = 1;
  }
}
