services:
  caddy:
    image: caddy:2.10.2
    env_file:
      - ./.env.edge
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - smev-api
      - smev-billing
      - smev-license-service
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
