/**
 * Centralized Legal & Tier Discipline Statements
 * Governs the §15 legal posture and §16 tier discipline watermarks for Hepar output.
 */

export const LEGAL_POSTURE = {
    SECTION_15_DISCLAIMER: `
LEGAL DISCLAIMER (§15 POSTURE):
The findings, risk indices, and structural intelligence contained in this document are generated by autonomous analytic systems (Hepar/Cortex/Synapse). 
This document is strictly for informational and governance review purposes. It does NOT constitute financial advice, an audit guarantee, or a legally binding risk assessment.
Sovereign Monad assumes no liability for capital loss, governance exploitation, or systemic failure related to the protocol described herein.
`,

    DISPUTE_PROTOCOL: `
DISPUTE & CORRECTION PROTOCOL:
If the protocol team identifies factual inaccuracies or wishes to contest the causal drivers assigned by Cortex, please submit a formal correction request to our LightVerify ingestion queue at:
https://hepar-commercial-pipeline.azurewebsites.net/api/hepar-dispute-queue
`
};

export const TIER_DISCIPLINE = {
    ADVISORY_WATERMARK: `
⚠️ ADVISORY TIER ONLY — NOT FOR COMMERCIAL DECISION ⚠️
This assessment was generated before Hepar achieved >90% precision in live-telemetry validation. 
It must not be used as the sole basis for capital allocation or protocol treasury deployment.
`
};
